services:
  dwarf-smagicshop.api:
    image: mrmoonshield/dwarf-smagicshop
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - seq
      - minio
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  postgres:
    image: postgres
    container_name: dwarf_s_magic_shop_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - 5341:5341
      - 8081:80
    environment:
      - ACCEPT_EULA=Y
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - dwarf-smagicshop.api
    restart: always
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

volumes:
  postgres-data:
  minio_data:
  mongo_data:
  rabbitmq_data:

